import random

class Answer_Book:
    database = {
        1: {'english': 'YOU WILL NOT BE DISAPPOINTED', 'chinese': '你不会失望的'},
        2: {'english': 'SHOW YOUR APPRECIATION', 'chinese': '展示你的感激之情'},
        3: {'english': 'YOUR ACTIONS WILL IMPROVE THINGS', 'chinese': '你的行动将改善事物'},
        4: {'english': 'DON’T BET ON IT', 'chinese': '不要赌'},
        5: {'english': 'ADOPT AN ADVENTUROUS ATTITUDE', 'chinese': '采取冒险的态度'},
        6: {'english': 'FOLLOW THE ADVICE OF EXPERTS', 'chinese': '听取专家意见'},
        7: {'english': 'YOU COULD FIND YOURSELF UNABLE TO COMPROMISE', 'chinese': '你可能会发现自己无法做到'},
        8: {'english': 'FOCUS ON YOUR HOME LIFE', 'chinese': '专注于你的家庭生活'},
        9: {'english': 'INVESTIGATE AND THEN ENJOY IT', 'chinese': '调查然后享受它'},
        10: {'english': 'DEFINITELY', 'chinese': '无疑'},
        11: {'english': 'ONLY DO IT ONCE', 'chinese': '只做一次'},
        12: {'english': 'YOU MAY HAVE OPPOSITION', 'chinese': '你可能会遇到反对'},
        13: {'english': 'IT WILL REMAIN UNPREDICTABLE', 'chinese': '它将保持不可预测'},
        14: {'english': 'YOU’LL NEED TO TAKE THE INITIATIVE', 'chinese': '你需要主动'},
        15: {'english': 'CONSIDER IT AN OPPORTUNITY', 'chinese': '认为这是机会'},
        16: {'english': 'BE DELIBERATE', 'chinese': '深思熟虑'},
        17: {'english': 'ABSOLUTELY NOT', 'chinese': '绝对不'},
        18: {'english': 'EXPLORE IT WITH PLAYFUL CURIOSITY', 'chinese': '铆足你的好奇心去探索'},
        19: {'english': 'PERHAPS, WHEN YOU’RE OLDER', 'chinese': '也许吧，当你长大时'},
        20: {'english': 'BE DELIGHTFULLY SURE OF IT', 'chinese': '愉快地确定'},
        21: {'english': 'BETTER TO WAIT', 'chinese': '最好等等'},
        22: {'english': 'REPRIORITIZE WHAT IS IMPORTANT', 'chinese': '轻重缓急'},
        23: {'english': 'IT SEEMS ASSURED', 'chinese': '看来有戏'},
        24: {'english': 'CREATE MORE SPACE FOR IT', 'chinese': '创造更多空间'},
        25: {'english': 'DO IT EARLY', 'chinese': '趁早行动'},
        26: {'english': 'KEEP IT TO YOURSELF', 'chinese': '给你自己留着'},
        27: {'english': 'ALLOW YOURSELF TO REST FIRST', 'chinese': '先让自己休息'},
        28: {'english': 'IT IS SENSIBLE', 'chinese': '这是明智的'},
        29: {'english': 'YOU’LL HAVE TO MAKE IT UP AS YOU GO', 'chinese': '你得边做边想，随机应变'},
        30: {'english': 'STARTLING EVENTS MAY OCCUR AS A RESULT', 'chinese': '可能会发生出乎意料的事件'},
        31: {'english': 'THE ANSWER MAY COME TO YOU IN ANOTHER LANGUAGE', 'chinese': '答案可能以其他语言呈现给你'},
        32: {'english': 'YOU WILL NEED TO ACCOMMODATE', 'chinese': '你将需要包容'},
        33: {'english': 'DOUBT IT', 'chinese': '质疑'},
        34: {'english': 'IT WILL BRING GOOD LUCK', 'chinese': '它会带来好运'},
        35: {'english': 'IT MAY BE CHALLENGING, BUT YOU WILL FIND VALUE IN IT',
             'chinese': '这可能是具有挑战性的，但你能行'},
        36: {'english': 'BE PATIENT', 'chinese': '要有耐心'},
        37: {'english': 'YOU WILL FIND OUT EVERYTHING YOU’LL NEED TO KNOW', 'chinese': '你会发现一切'},
        38: {'english': 'THERE IS A SUBSTANTIAL LINK TO ANOTHER SITUATION', 'chinese': '与另一个有重要联系'},
        39: {'english': 'WATCH AND SEE WHAT HAPPENS', 'chinese': '静观其变'},
        40: {'english': 'YOU KNOW BETTER NOW THAN EVER BEFORE', 'chinese': '你比以往任何时间都清楚'},
        41: {'english': 'IT WILL AFFECT HOW OTHERS SEE YOU', 'chinese': '它将影响别人看你的方式'},
        42: {'english': 'RECONSIDER YOUR APPROACH', 'chinese': '重新考虑你的方法'},
        43: {'english': 'YOU’LL BE HAPPY YOU DID', 'chinese': '你会很高兴你这样做了'},
        44: {'english': 'GET IT IN WRITING', 'chinese': '立此存照'},
        45: {'english': 'UNFAVORABLE AT THIS TIME', 'chinese': '目前不利'},
        46: {'english': 'IT IS NOT SOMETHING TO BE TAKEN LIGHTLY', 'chinese': '不可轻视'},
        47: {'english': 'UPGRADE IN ANY WAY YOU CAN', 'chinese': '尽一切可能升级'},
        48: {'english': 'IF YOU DO AS YOU’RE TOLD', 'chinese': '如果你按照指示行事'},
        49: {'english': 'IF IT’S DONE WELL; IF NOT, DON’T DO IT AT ALL',
             'chinese': '如果做得好，就做，如果做得不好，就不要做'},
        50: {'english': 'DON’T ASK FOR ANY MORE AT THIS TIME', 'chinese': '停止索求'},
        51: {'english': 'AVOID THE FIRST SOLUTION', 'chinese': '避免第一种方案'},
        52: {'english': 'YOU’LL GET THE FINAL WORD', 'chinese': '你说了算'},
        53: {'english': 'PROCEED AT A MORE RELAXED PACE', 'chinese': '放缓脚步'},
        54: {'english': 'THE BEST SOLUTION MAY NOT BE THE OBVIOUS ONE', 'chinese': '可能不是最佳解决方案'},
        55: {'english': 'REMAIN FLEXIBLE', 'chinese': '保持灵活'},
        56: {'english': 'RESPECT THE RULES', 'chinese': '尊重规则'},
        57: {'english': 'TAKE THE LEAD', 'chinese': '带头行动'},
        58: {'english': 'CHOOSE YOUR WORDS THOUGHTFULLY', 'chinese': '字斟句酌'},
        59: {'english': 'YOU MAY BE HANGING ON TO AN OUTDATED IDEAL', 'chinese': '你可能会坚持'},
        60: {'english': 'THERE MAY BE A STRUGGLE', 'chinese': '可能会有一场斗争'},
        61: {'english': 'YOU’LL HAVE THE ENTHUSIASM YOU’LL NEED', 'chinese': '你会拥有热情'},
        62: {'english': 'PROVIDED YOU SAY “THANK YOU”', 'chinese': '只要你说 "谢谢"'},
        63: {'english': 'ENJOY THE EXPERIENCE', 'chinese': '享受这场体验'},
        64: {'english': 'APPROACH CAUTIOUSLY', 'chinese': '慎入'},
        65: {'english': 'BE YOUR OWN BEST ADVOCATE', 'chinese': '做自己最好的拥护者'},
        66: {'english': 'BE HAPPY FOR ANOTHER', 'chinese': '为别人感到开心'},
        67: {'english': 'PAY ATTENTION TO THE DETAILS', 'chinese': '注意细节'},
        68: {'english': 'WATCH YOUR STEP AS YOU GO', 'chinese': '检查你的步骤'},
        69: {'english': 'SPEAK UP ABOUT IT', 'chinese': '大声说出来'},
        70: {'english': 'DON’T HESITATE', 'chinese': '不要犹豫'},
        71: {'english': 'THIS IS A GOOD TIME TO MAKE A NEW PLAN', 'chinese': '现在是制定新计划的好时机'},
        72: {'english': 'MOVE ON', 'chinese': '继续前进'},
        73: {'english': 'A STRONG COMMITMENT WILL ACHIEVE GOOD RESULTS', 'chinese': '坚定的承诺会取得良好的结果'},
        74: {'english': 'IT MAY NOT BE LOGICAL', 'chinese': '未必合乎逻辑'},
        75: {'english': 'THERE IS NO GUARANTEE', 'chinese': '不保证'},
        76: {'english': 'THE CIRCUMSTANCES COULD CHANGE VERY QUICKLY', 'chinese': '情况可能会很快改变'},
        77: {'english': 'DON’T GET CAUGHT UP IN YOUR EMOTIONS', 'chinese': '不要沉浸在情绪中'},
        78: {'english': 'SHIFT YOUR FOCUS', 'chinese': '转变你的注意力'},
        79: {'english': 'IT IS SIGNIFICANT', 'chinese': '意义重大'},
        80: {'english': 'REPRIORITIZE WHAT IS IMPORTANT', 'chinese': '轻重缓急'},
        81: {'english': 'MAKE A LIST OF WHY NOT', 'chinese': '列出来为什么不做的原因'},
        82: {'english': 'DON’T WAIT', 'chinese': '不要等待'},
        83: {'english': 'TAKE YOUR TIME', 'chinese': '慢慢来'},
        84: {'english': 'THERE IS GOOD REASON TO BE OPTIMISTIC', 'chinese': '有充分的理由乐观'},
        85: {'english': 'IT IS SOMETHING YOU WON’T FORGET', 'chinese': '让你终生难忘'},
        86: {'english': 'SEEK OUT MORE OPTIONS', 'chinese': '寻求更多选择'},
        87: {'english': 'FOLLOW THROUGH ON YOUR OBLIGATIONS', 'chinese': '履行义务'},
        88: {'english': 'DEAL WITH IT LATER', 'chinese': '稍后处理'},
        89: {'english': 'REVEAL YOUR THOUGHTS TO A TRUSTED CONFIDANTE', 'chinese': '向知己吐露心声'},
        90: {'english': 'FOLLOW SOMEONE ELSE’S LEAD', 'chinese': '跟随别人的领导'},
        91: {'english': 'YOU COULD FIND YOURSELF UNABLE TO COMPROMISE', 'chinese': '你会发现自己无法妥协'},
        92: {'english': 'MAKE A LIST OF WHY', 'chinese': '列出为什么'},
        93: {'english': 'TAKE A CHANCE', 'chinese': '抓住机会'},
        94: {'english': 'YOUR ACTIONS WILL IMPROVE THINGS', 'chinese': '你的行动会事物更好'},
        95: {'english': 'ASK FOR HELP', 'chinese': '寻求帮助'},
        96: {'english': 'KNOW WHEN IT’S TIME TO GO', 'chinese': '见好就收'},
        97: {'english': 'ACCEPT A CHANGE TO YOUR ROUTINE', 'chinese': '接受对你的日常生活的改变'},
        98: {'english': 'YOU’LL NEED TO TAKE THE INITIATIVE', 'chinese': '你需要主动出击'},
        99: {'english': 'YOU’LL HAVE TO COMPROMISE', 'chinese': '你必须妥协'},
        100: {'english': 'YOU NEED MORE INFORMATION', 'chinese': '你需要更多信息'},
        101: {'english': 'TRUST YOUR ORIGINAL THOUGHT', 'chinese': '相信你最初的想法'},
        102: {'english': 'SEEK OUT THE PATH OF LEAST RESISTANCE', 'chinese': '另辟蹊径'},
        103: {'english': 'IT WILL CREATE A STIR', 'chinese': '会引起轰动'},
        104: {'english': 'YOU’LL OVERCOME ANY OBSTACLES', 'chinese': '你会克服任何障碍'},
        105: {'english': 'IT WOULD BE BETTER TO FOCUS ON YOUR WORK', 'chinese': '最好专注于你的工作'},
        106: {'english': 'IT WILL BE A PLEASURE', 'chinese': '这将是一件愉快的事情'},
        107: {'english': 'BE MORE GENEROUS', 'chinese': '更加慷慨'},
        108: {'english': 'BET ON IT', 'chinese': '赌一把'},
        109: {'english': 'GOOD THINGS ARE SEEKING YOU OUT', 'chinese': '好消息在等着你'},
        110: {'english': 'DON’T LEAVE ROOM FOR REGRET', 'chinese': '不要留下后悔的余地'},
        111: {'english': 'MAKE A CONTRIBUTION', 'chinese': '做出贡献'},
        112: {'english': 'MISHAPS ARE HIGHLY PROBABLE', 'chinese': '极有可能发生事故'},
        113: {'english': 'PRESS FOR CLOSURE', 'chinese': '按下关闭按钮'},
        114: {'english': 'REALIZE THAT TOO MANY CHOICES CAN BE AS DIFFICULT AS TOO FEW',
              'chinese': '认识到选择太多和选择太少一样困难'},
        115: {'english': 'YES', 'chinese': '是'},
        116: {'english': 'LISTEN CAREFULLY; THEN YOU WILL KNOW', 'chinese': '仔细倾听，你会知道'},
        117: {'english': 'THE ANSWER IS IN YOUR BACKYARD', 'chinese': '答案就在你家后院'},
        118: {'english': 'LAUGH ABOUT IT', 'chinese': '一笑置之'},
        119: {'english': 'LET YOUR EMOTIONS GUIDE YOU', 'chinese': '让你的情绪引导你'},
        120: {'english': 'OTHERS WILL DEPEND ON YOUR CHOICES', 'chinese': '其他取决于你的选择'},
        121: {'english': 'LET IT GO', 'chinese': '放手'},
        122: {'english': 'IT’S TIME FOR YOU TO GO', 'chinese': '是时候走'},
        123: {'english': 'DON’T BE DISTRACTED', 'chinese': '不要分心'},
        124: {'english': 'GIVE IT ALL YOU’VE GOT', 'chinese': '全力以赴'},
        125: {'english': 'YOU DON’T REALLY CARE', 'chinese': '你并不真的在乎'},
        126: {'english': 'YOU’LL NEED TO CONSIDER OTHER WAYS', 'chinese': '你需要考虑其他方法'},
        127: {'english': 'A YEAR FROM NOW IT WON’T MATTER', 'chinese': '一年后就无所谓了'},
        128: {'english': 'FOLLOW THE ADVICE OF EXPERTS', 'chinese': '听从专家建议'},
        129: {'english': 'IT COULD BE EXTRAORDINARY', 'chinese': '这可能是非同寻常的'},
        130: {'english': 'COUNT TO TEN; ASK AGAIN', 'chinese': '数到十；再问一遍'},
        131: {'english': 'ACT AS THOUGH IT IS ALREADY REAL', 'chinese': '就好像它已经是真实的一样行事'},
        132: {'english': 'SETTING PRIORITIES WILL BE A NECESSARY PART OF THE PROCESS',
              'chinese': '设定优先级将是这个过程的必要部分。'},
        133: {'english': 'USE YOUR IMAGINATION', 'chinese': '发挥你的想象力'},
        134: {'english': 'IT’S GONNA BE GREAT', 'chinese': '会很棒的'},
        135: {'english': 'TO ENSURE THE BEST DECISION, BE CALM', 'chinese': '为了确保最好的决定，保持冷静'},
        136: {'english': 'WAIT', 'chinese': '等待'},
        137: {'english': 'YOU’LL HAVE TO MAKE IT UP AS YOU GO', 'chinese': '你得边做边想，随机应变'},
        138: {'english': 'FOLLOW THE DIRECTIONS', 'chinese': '遵循指示'},
        139: {'english': 'UNQUESTIONABLY', 'chinese': '毫无疑问'},
        140: {'english': 'OF COURSE', 'chinese': '当然'},
        141: {'english': 'LOOK FOR WHAT MAY BE HIDDEN', 'chinese': '寻找可能隐藏的内容'},
        142: {'english': 'YOU KNOW BETTER NOW THAN EVER BEFORE', 'chinese': '你现在比以往任何时候都更了解'},
        143: {'english': 'TRUST YOUR INTUITION', 'chinese': '相信直觉'},
        144: {'english': 'DON’T MISS AN OPPORTUNITY', 'chinese': '机不可失'},
        145: {'english': 'ASK YOUR FATHER', 'chinese': '问问父亲'},
        146: {'english': 'ASK YOUR MOTHER', 'chinese': '问问妈妈'},
        147: {'english': 'PERHAPS, WHEN YOU’RE OLDER', 'chinese': '也许，在你年纪稍长时'},
        148: {'english': 'MAYBE', 'chinese': '也许'},
        149: {'english': 'FINISH SOMETHING ELSE FIRST', 'chinese': '先完成其他事情'},
        150: {'english': 'YOU MAY HAVE OPPOSITION', 'chinese': '你可能会遭遇反对'},
        151: {'english': 'YOU ARE TOO CLOSE TO SEE', 'chinese': '近在眼前'},
        152: {'english': 'THE SITUATION IS UNCLEAR', 'chinese': '情况不明'},
        153: {'english': 'A SUBSTANTIAL EFFORT WILL BE REQUIRED', 'chinese': '需要付出巨大努力'},
        154: {'english': 'ALLOW YOURSELF TO REST FIRST', 'chinese': '先让自己休息'},
        155: {'english': 'THE CHANCE WILL NOT COME AGAIN SOON', 'chinese': '机不可失，时不再来'},
        156: {'english': 'THE ANSWER MAY COME TO YOU IN ANOTHER LANGUAGE', 'chinese': '答案可能以另一种语言呈现给你'},
        157: {'english': 'RECONSIDER YOUR APPROACH', 'chinese': '重新考虑你的做法'},
        158: {'english': 'IT WOULD BE INADVISABLE', 'chinese': '不宜'},
        159: {'english': 'THERE IS A SMALL PRICE TO PAY', 'chinese': '有一点小代价'},
        160: {'english': 'WAIT FOR A BETTER OFFER', 'chinese': '等待更好的条件'},
        161: {'english': 'SETTLE IT SOON', 'chinese': '尽快解决'},
        162: {'english': 'REMAIN OBJECTIVE', 'chinese': '保持客观'},
        163: {'english': 'YES, BUT DON’T FORCE IT', 'chinese': '是的，但不要强迫'},
        164: {'english': 'GET A CLEARER VIEW', 'chinese': '看清楚'},
        165: {'english': 'BE DELIGHTFULLY SURE OF IT', 'chinese': '愉快地确定它'},
        166: {'english': 'NOW YOU CAN', 'chinese': '现在可以'},
        167: {'english': 'PROVIDED YOU SAY “THANK YOU”', 'chinese': '只要你说 "谢谢"'},
        168: {'english': 'DON’T OVERDO IT', 'chinese': '适可而止'},
        169: {'english': 'IT WILL SUSTAIN YOU', 'chinese': '它将支持你'},
        170: {'english': 'IT COULD COST YOU', 'chinese': '这可能会让你付出代价'},
        171: {'english': 'ADOPT AN ADVENTUROUS ATTITUDE', 'chinese': '采取冒险的态度'},
        172: {'english': 'IT IS SURE TO MAKE THINGS INTERESTING', 'chinese': '一定会很有趣'},
        173: {'english': 'BE PRACTICAL', 'chinese': '脚踏实地'},
        174: {'english': 'ARE YOU READY?', 'chinese': '你准备好了吗？'},
        175: {'english': 'SAVE YOUR ENERGY', 'chinese': '节省你的能量'},
        176: {'english': 'PAY ATTENTION TO THE DETAILS', 'chinese': '注意细节'},
        177: {'english': 'IT IS CERTAIN', 'chinese': '可以肯定的'},
        178: {'english': 'IT IS UNCERTAIN', 'chinese': '这是不确定的'},
        179: {'english': 'THE OUTCOME WILL BE POSITIVE', 'chinese': '结果将是积极的'},
        180: {'english': 'YOU MAY HAVE TO DROP OTHER THINGS', 'chinese': '你可能需要放弃其他事情'},
        181: {'english': 'DON’T BE CONCERNED', 'chinese': '不要担心'},
        182: {'english': 'PREPARE FOR THE UNEXPECTED', 'chinese': '未雨绸缪'},
        183: {'english': 'TELL SOMEONE WHAT IT MEANS TO YOU', 'chinese': '告诉别人这对你意味着什么'},
        184: {'english': 'WHATEVER YOU DO, THE RESULTS WILL BE LASTING', 'chinese': '无论你做什么，效果都将是持久的'},
        185: {'english': 'KEEP AN OPEN MIND', 'chinese': '保持开放的心态'},
        186: {'english': 'IT’S A GOOD TIME TO MAKE PLANS', 'chinese': '制定计划的好时机'},
        187: {'english': 'IT MAY BE AMBITIOUS, BUT YOU WILL FIND VALUE IN IT',
              'chinese': '这或许是一个有野心的计划，但你会在其中找到价值'},
        188: {'english': 'IT IS WORTH THE TROUBLE', 'chinese': '不枉此行'},
        189: {'english': 'YOU’LL OVERCOME ANY OBSTACLES', 'chinese': '你会克服任何障碍'},
        190: {'english': 'RELATED ISSUES MAY SURFACE', 'chinese': '相关问题可能会浮出水面'},
        191: {'english': 'YOU ARE SURE TO HAVE SUPPORT', 'chinese': '一定会得到支持'},
        192: {'english': 'ASSISTANCE WOULD MAKE YOUR PROGRESS A SUCCESS', 'chinese': '协助将使你的进步取得成功'},
        193: {'english': 'COLLABORATION WILL BE THE KEY', 'chinese': '协作将是关键'},
        194: {'english': 'SEEK OUT MORE OPTIONS', 'chinese': '寻求更多选择'},
        195: {'english': 'TAKE CHARGE', 'chinese': '承担责任'},
        196: {'english': 'IT CANNOT FAIL', 'chinese': '它不会失败'},
        197: {'english': 'YOU MUST ACT NOW', 'chinese': '你必须立即行动'},
        198: {'english': 'RESPECT THE RULES', 'chinese': '尊重规则'},
        199: {'english': 'GENTLE PERSISTENCE WILL PAY OFF', 'chinese': '久久为功'},
        200: {'english': 'YOU COULD BE DISAPPOINTED', 'chinese': '你可能会失望'},
        201: {'english': 'IT MAY ALREADY BE A DONE DEAL', 'chinese': '可能已成定局'},
        202: {'english': 'FOLLOW THROUGH WITH YOUR GOOD INTENTIONS', 'chinese': '善始善终'},
        203: {'english': 'TAKE MORE TIME TO DECIDE', 'chinese': '需要更多时间决定'},
        204: {'english': 'FOLLOW THROUGH ON YOUR OBLIGATIONS', 'chinese': '履行义务'},
        205: {'english': 'DON’T BE PRESSURED INTO ACTING TOO QUICKLY', 'chinese': '不要急于求成'},
        206: {'english': 'DON’T IGNORE THE OBVIOUS', 'chinese': '不要忽视显而易见的事情'},
        207: {'english': 'OTHERS WILL RESPECT YOUR CHOICES', 'chinese': '其他人会尊重你的选择'},
        208: {'english': 'DON’T BE TOO PRACTICAL', 'chinese': '别太实际'},
        209: {'english': 'BE A GOOD ROLE MODEL', 'chinese': '以身作则'},
        210: {'english': 'IT’S NOT WORTH A STRUGGLE', 'chinese': '不值得努力'},
        211: {'english': 'LISTEN CAREFULLY; THEN YOU WILL KNOW', 'chinese': '仔细倾听，你会知道'},
        212: {'english': 'DON’T FORGET TO HAVE FUN', 'chinese': '别忘了享受生活'},
        213: {'english': 'DON’T DOUBT IT', 'chinese': '不要怀疑'},
        214: {'english': 'A STRONG COMMITMENT WILL ACHIEVE GOOD RESULTS', 'chinese': '坚定的决心将会取得良好的成果'},
        215: {'english': 'TRY A MORE UNLIKELY SOLUTION', 'chinese': '试试更不可能的办法'},
        216: {'english': 'LEAVE BEHIND OLD SOLUTIONS', 'chinese': '弃旧图新'},
        217: {'english': 'KEEP IT TO YOURSELF', 'chinese': '留给自己'},
        218: {'english': 'WATCH YOUR STEP AS YOU GO', 'chinese': '慎行'},
        219: {'english': 'EXPLORE IT WITH PLAYFUL CURIOSITY', 'chinese': '铆足你的好奇心去探索'},
        220: {'english': 'DON’T BE TOO DEMANDING', 'chinese': '别太苛求'},
        221: {'english': 'DON’T LEAVE ROOM FOR REGRET', 'chinese': '不要留下遗憾的空间'},
        222: {'english': 'ACT AS THOUGH IT IS ALREADY REAL', 'chinese': '就好像它已经是真实的一样行事'},
        223: {'english': 'IT ISN’T PERSONAL', 'chinese': '这不是针对个人的'},
        224: {'english': 'BE PERSISTENT', 'chinese': '持之以恒'},
        225: {'english': 'CHOOSE WHAT WILL MAKE YOU HAPPY', 'chinese': '选择快乐'},
        226: {'english': 'DON’T LET MONEY DECIDE IT', 'chinese': '不要让金钱来决定'},
        227: {'english': 'IT WILL WORK ITSELF OUT', 'chinese': '会解决的'},
        228: {'english': 'IF IT’S TOO DIFFICULT, MAYBE IT’S NOT YOURS', 'chinese': '如果太难，也许就不是你的了'},
        229: {'english': 'IT COULD MEAN THAT YOU MAY HAVE TO DO SOMETHING THAT YOU’VE NEVER DONE',
              'chinese': '这可能意味着你可能需要做一些你从未尝试过的事情。'},
        230: {'english': 'DECIDE WHERE YOU WANT TO BE AND HEAD IN THAT DIRECTION',
              'chinese': '确定你想去的地方，并朝着那个方向前进'},
        231: {'english': 'CAST YOUR NET WIDER', 'chinese': '扩大范围'},
        232: {'english': 'MAKE NO ASSUMPTIONS', 'chinese': '不要做任何假设'},
        233: {'english': 'RESPECT THE FUNDAMENTALS', 'chinese': '尊重基本原则'},
        234: {'english': 'BE RESOURCEFUL', 'chinese': '充分利用资源'},
        235: {'english': 'FIND MORE TIME', 'chinese': '寻找更多时间'},
        236: {'english': 'NOTHING WILL COMPARE', 'chinese': '无与伦比'},
        237: {'english': 'IT WILL BE AN OPPORTUNITY', 'chinese': '这将是一个机会。'},
        238: {'english': 'DON’T GIVE UP YOUR RIGHT TO WAIT', 'chinese': '不要放弃等待的权利'},
        239: {'english': 'BE DELIBERATE', 'chinese': '深思熟虑'},
        240: {'english': 'WHY IS IT IMPORTANT TO YOU?', 'chinese': '为什么它对你很重要？'},
        241: {'english': 'DON’T LET THE MOMENT PASS', 'chinese': '机不可失，时不再来'},
        242: {'english': 'YOU’LL GET WHAT YOU SETTLE FOR', 'chinese': '你会得到你想要的'},
        243: {'english': 'CHOOSE WHATEVER WILL HELP YOU TO GROW', 'chinese': '选择任何能帮助你成长的'},
        244: {'english': 'BE KIND', 'chinese': '向善'},
        245: {'english': 'REALIZE THAT TOO MANY CHOICES CAN BE AS DIFFICULT AS TOO FEW',
              'chinese': '认识到选择太多和选择太少一样困难'},
        246: {'english': 'TAKE A CHANCE', 'chinese': '抓住机会'},
        247: {'english': 'YOU WILL HAVE EVERYTHING NECESSARY FOR YOUR SUCCESS', 'chinese': '你将获得成功所需的一切'},
        248: {'english': 'OTHERS MAY NOT APPROVE', 'chinese': '他人未必赞同'},
        249: {'english': 'YOU’LL HAVE THE STRENGTH YOU’LL NEED', 'chinese': '你将拥有你需要的力量'},
        250: {'english': 'INITIATE AN ADVENTURE', 'chinese': '开始冒险'},
        251: {'english': 'BE TACTFUL', 'chinese': '机智一点'},
        252: {'english': 'YOU’LL NEED TO CONSIDER OTHER WAYS', 'chinese': '你需要考虑其他方法'},
        253: {'english': 'FIGURE OUT A WAY', 'chinese': '想办法'},
        254: {'english': 'IT COULD BE A MATTER OF PRIDE', 'chinese': '这可能是一个引以为豪的事情'},
        255: {'english': 'PURSUE MORE VARIETY', 'chinese': '追求多样化'},
        256: {'english': 'DON’T GET CAUGHT UP IN YOUR EMOTIONS', 'chinese': '不要陷入自己的情绪之中'},
        257: {'english': 'PITCH IN WHATEVER YOU CAN', 'chinese': '尽你所能'},
        258: {'english': 'ARRIVE EARLY', 'chinese': '提前到达'},
        259: {'english': 'NO MATTER WHAT', 'chinese': '无论如何'},
        260: {'english': 'YOU ARE TOO CLOSE TO SEE', 'chinese': '不识庐山真面目'},
        261: {'english': 'YES', 'chinese': '是的'},
        262: {'english': 'DON’T TAKE A CHANCE', 'chinese': '不要冒险'},
        263: {'english': 'IT IS NOT SOMETHING TO BE TAKEN LIGHTLY', 'chinese': '不可掉以轻心'},
        264: {'english': 'BE CONTENT TO LEAVE WELL ENOUGH ALONE', 'chinese': '善罢甘休'},
        265: {'english': 'TOO MUCH ATTENTION IS ON THE DETAILS', 'chinese': '过于注重细节'},
        266: {'english': 'KEEP IT LIGHT', 'chinese': '保持轻松'},
        267: {'english': 'GET MORE SLEEP', 'chinese': '多睡觉'},
        268: {'english': 'RECONSIDER ANOTHER POSSIBILITY', 'chinese': '另想办法'},
        269: {'english': 'IT MAY NOT BE LOGICAL', 'chinese': '未必合乎逻辑'},
        270: {'english': 'THE ANSWER IS IN YOUR BACKYARD', 'chinese': '答案就在你的身后'},
        271: {'english': 'MAKE A CONTRIBUTION', 'chinese': '做出贡献'},
        272: {'english': 'USE YOUR IMAGINATION', 'chinese': '发挥想象力'},
        273: {'english': 'KNOW NO LIMITATIONS', 'chinese': '无止境'},
        274: {'english': 'BUILD SOMETHING BIGGER', 'chinese': '更上一层楼'},
        275: {'english': 'AIM HIGHER', 'chinese': '志存高远'},
        276: {'english': 'TAKE IT IN STRIDE', 'chinese': '泰然处之'},
        277: {'english': 'BE A GOOD SPORT', 'chinese': '做个好运动员'},
        278: {'english': 'TAKE THE LEAD', 'chinese': '带头行动'},
        279: {'english': 'THERE IS A SMALL PRICE TO PAY', 'chinese': '有一点小代价'},
        280: {'english': 'DON’T BE TOO CRITICAL', 'chinese': '不要太苛刻'},
        281: {'english': 'PUT YOUR FEELINGS IN THE RIGHT PLACE', 'chinese': '正确对待感情'},
        282: {'english': 'IDENTIFY WHAT MATTERS ABOUT IT', 'chinese': '确定什么是重要的'},
        283: {'english': 'HOW THINGS TURN OUT WILL DEPEND ON YOU', 'chinese': '事在人为'},
        284: {'english': 'LOOK FOR WHAT MAY BE HIDDEN', 'chinese': '寻找可能隐藏的内容'},
        285: {'english': 'LET YOUR EMOTIONS GUIDE YOU', 'chinese': '让你的情绪引导你'},
        286: {'english': 'REVEAL YOUR THOUGHTS TO A TRUSTED CONFIDANTE', 'chinese': '向知己吐露心声'},
        287: {'english': 'TAKE A CLOSER LOOK', 'chinese': '仔细看'},
        288: {'english': 'DON’T BE CONCERNED', 'chinese': '别在意'},
        289: {'english': 'YOU CAN DO THIS ON YOUR OWN', 'chinese': '你可以自己做到'},
        290: {'english': 'ASK FOR HELP', 'chinese': '求援'},
        291: {'english': 'CREATE MORE SPACE FOR IT', 'chinese': '创造更多'},
        292: {'english': 'DIVERT YOUR ATTENTION', 'chinese': '转移视线'},
        293: {'english': 'WHAT DO YOU WANT?', 'chinese': '想想你想要什么？'},
        294: {'english': 'DO YOUR BEST TO SET THE STANDARD', 'chinese': '尽量确立标准'},
        295: {'english': 'THERE IS GOOD REASON TO BE OPTIMISTIC', 'chinese': '我们有理由感到乐观'},
        296: {'english': 'DON’T BE DISTRACTED', 'chinese': '别分心'},
        297: {'english': 'ENJOY A NEW SETTING', 'chinese': '享受新环境'},
        298: {'english': 'YOU WILL NEED TO ACCOMMODATE', 'chinese': '你需要做出妥协'},
        299: {'english': 'REMAIN OBJECTIVE', 'chinese': '保持客观'},
        300: {'english': 'TELL SOMEONE WHAT IT MEANS TO YOU', 'chinese': '告诉别人这对你意味着什么'},
        301: {'english': 'CONSIDER IT AN OPPORTUNITY', 'chinese': '以此为契机'},
        302: {'english': 'SEEK OUT THE PATH OF LEAST RESISTANCE', 'chinese': '另辟蹊径'},
        303: {'english': 'GOOD THINGS ARE SEEKING YOU OUT', 'chinese': '好消息在等着你'},
        304: {'english': 'IT WON’T MATTER WHEN YOU DO, BUT THAT YOU DO',
              'chinese': '什么时候做不重要，而是你真正去做了'},
        305: {'english': 'YOU MAY BE HANGING ON TO AN OUTDATED IDEAL', 'chinese': '你可能还在固守一个过时的理念'},
        306: {'english': 'IT’LL CHANGE YOUR LUCK', 'chinese': '这会改变你的运气'},
        307: {'english': 'DON’T RESIST', 'chinese': '不要对抗'},
        308: {'english': 'FOLLOW THE DIRECTIONS', 'chinese': '遵循指示'},
        309: {'english': 'THE BEST SOLUTION MAY BE THE OBVIOUS ONE', 'chinese': '最好的解决方案可能就是最直接的'},
        310: {'english': 'DON’T BE TOO CAUTIOUS', 'chinese': '别太谨慎'},
        311: {'english': 'YOU MAY REGRET IT', 'chinese': '你可能会后悔'},
        312: {'english': 'IS IT IMPORTANT TO YOU?', 'chinese': '这对你来说重要吗？'},
        313: {'english': 'CHOOSE YOUR WORDS CAREFULLY', 'chinese': '谨言慎行'},
        314: {'english': 'LIMIT THE OPTIONS', 'chinese': '选择有限'},
        315: {'english': 'FOCUS YOUR ATTENTION', 'chinese': '集中注意力'},
        316: {'english': 'SHOULDN’T YOU BE OUTSIDE PLAYING?', 'chinese': '你不应该在外面玩吗？'},
        317: {'english': 'WOULD IT BE A PLEASURE?', 'chinese': '你乐意吗？'},
        318: {'english': 'BE ON TIME', 'chinese': '准时'},
        319: {'english': 'ASK YOUR FATHER', 'chinese': '问问父亲'},
        320: {'english': 'ASK YOUR MOTHER', 'chinese': '问问妈妈'},
        321: {'english': 'TAKE YOUR TIME', 'chinese': '慢慢来'},
        322: {'english': 'YES, BUT DON’T FORCE IT', 'chinese': '是的，但不要强迫'},
        323: {'english': 'THERE IS MORE TO KNOW', 'chinese': '还有更多需要了解'},
        324: {'english': 'FIND OUT THE FACTS', 'chinese': '弄清事实'},
        325: {'english': 'NOT IF YOU’RE ALONE', 'chinese': '一个人，不行'},
        326: {'english': 'UNCOVER MORE DETAILS', 'chinese': '揭示更多细节'},
        327: {'english': 'YOUR HEART ISN’T IN IT', 'chinese': '你心不在焉'},
        328: {'english': 'BE HAPPY FOR ANOTHER', 'chinese': '替别人高兴'},
        329: {'english': 'YOU ARE FAVORED', 'chinese': '你备受青睐'},
        330: {'english': 'NEVER', 'chinese': '从来没有'},
        331: {'english': 'A YEAR FROM NOW IT WON’T MATTER', 'chinese': '一年后就无所谓了'},
        332: {'english': 'ARE YOU READY?', 'chinese': '你准备好了吗？'},
        333: {'english': 'YOU MUST', 'chinese': '你必须'},
        334: {'english': 'NO', 'chinese': '不'},
        335: {'english': 'CONSERVE YOUR RESOURCES', 'chinese': '节约资源'},
        336: {'english': 'BE A GOOD ROLE MODEL', 'chinese': '以身作则'},
        337: {'english': 'NEGOTIATE A BETTER DEAL', 'chinese': '讨价还价'},
        338: {'english': 'FAVOR THE GOOD THINGS', 'chinese': '优先选择好的事物'},
        339: {'english': 'DON’T LET IT BE RUINED BY REASON', 'chinese': '不要让它被理性破坏'},
        340: {'english': 'SLEEP ON IT', 'chinese': '睡一觉再说'},
        341: {'english': 'DO YOUR BEST', 'chinese': '尽力而为'},
        342: {'english': 'IT IS NOT SIGNIFICANT', 'chinese': '无足轻重'},
        343: {'english': 'YOU HAVE SO MUCH TO OFFER', 'chinese': '你大有可为'},
        344: {'english': 'KNOW WHAT’S IMPORTANT TO YOU', 'chinese': '知道什么对你重要'},
        345: {'english': 'YOU DESERVE THE BEST', 'chinese': '你值得最好的'},
        346: {'english': 'BETTER THINGS ARE SEEKING YOU OUT', 'chinese': '更美好的事物在等着你'},
        347: {'english': 'IT’S UP TO YOU', 'chinese': '看你的了'},
        348: {'english': 'CHOOSE WHAT MAKES YOU HAPPY', 'chinese': '选择让你快乐的事'},
        349: {'english': 'LET YOUR HEART LEAD THE WAY', 'chinese': '让心引领方向'},
        350: {'english': 'DON’T GET CAUGHT UP IN THE DETAILS', 'chinese': '不要纠结于细节'},
    }
    def __init__(self):
        self.database = self.database

    def get_answer(self):
        # 随机选择一个键
        key = random.choice(list(self.database.keys()))
        # 获取对应的英文和中文内容
        answer = self.database[key]
        # 返回格式化的字符串
        return f"{answer['english']}\n{answer['chinese']}"

if __name__ == '__main__':
    print(Answer_Book().get_answer())
